#config_version=5

shot_profiles:
  three_indicator:
    states:
      - name: lit
        show: ww_three_lit
      - name: lit_wiggler
        show: ww_three_lit_wiggler
      - name: unlit
        show: ww_three_unlit
  one_indicator:
    states:
      - name: lit
        show: ww_one_lit
      - name: lit_wiggler
        show: ww_one_lit_wiggler
      - name: unlit
        show: ww_one_unlit

