#config_version=5

shows:
  ww_three_lit:
    - duration: 1
      lights:
        (a): blue
        (b): blue
        (c): blue
  ww_three_lit_wiggler:
    - duration: 1
      lights:
        (a): red
        (b): red
        (c): red
  ww_three_narrowing:
    - duration: .05
      lights:
        (a): stop
        (b): blue
        (c): blue
    - duration: .05
      lights:
        (a): stop
        (b): stop
        (c): blue
    - duration: .05
      lights:
        (a): stop
        (b): stop
        (c): stop
  ww_three_unlit:
    - duration: -1
      lights:
        (a): stop
        (b): stop
        (c): stop
  ww_one_lit:
    - duration: 1
      lights:
        (a): blue
  ww_one_lit_wiggler:
    - duration: 1
      lights:
        (a): red
  ww_one_narrowing:
    - duration: 1
      lights:
        (a): stop
  ww_one_unlit:
    - duration: -1
      lights:
        (a): stop

