#config_version=5

timers:
  ww_roving_shot_update:
    tick_interval: .2s
    end_value: 1
    restart_on_complete: True
    control_events:
      - action: start
        event: ww_state_search_started
  # timer used to give feedback to the player they've narrowed the shots on the playfield
  ww_narrowed:
    # end value doesnt matter
    end_value: 15
    tick_interval: .05s
    control_events:
      - action: start
        event: ww_code_narrowed_start
      - action: reset
        event: ww_state_search_started
  # timer used to give feedback to the player they've caught the wiggler before restarting
  ww_collected_timeout:
    end_value: 1
    control_events:
      - action: start
        event: ww_state_collected_started
