#config_version=5

mode:
  start_events: song_select_2_status_running
  priority: 200
  code: wiggly_world.WigglyWorld
  stop_events: timer_song_countdown_complete

config:
  - shot_profiles
  - shots
  - shows
  - slides
  - state_machines
  - sound_player
  - timers
  - widgets

show_player:
  ww_state_intro_started:
    ww_intro:
      loops: 0
      events_when_played: song_intro_played
      events_when_completed: song_intro_complete

slide_player:
  ww_state_intro_started:
    ww:
      action: play
  ww_state_search_started:
    ww:
      action: remove
  
