#config_version=5

mode:
  start_events: dev_start_third
  stop_events: dev_award_letter

config:
  - shots.yaml

event_player:
  mode_third_started.1: third_enable_ramp_left_lower
  mode_third_started.2: third_enable_orbit_left
  mode_third_started.3: third_enable_ramp_right
  mode_third_started.4: third_enable_orbit_right
  mode_third_started.5: third_enable_bash_left
  mode_third_started.6: third_enable_bash_diagonal_left
  mode_third_started.7: third_enable_bash_center
  mode_third_started.8: third_enable_bash_diagonal_right
  mode_third_started.9: third_enable_bash_right

accruals:
  third:
    events:
      - sh_third_ramp_left_lower_hit
      - sh_third_orbit_left_hit
      - sh_third_ramp_right_hit
      - sh_third_orbit_right_hit
      - sh_third_bash_left_hit
      - sh_third_bash_diagonal_left_hit
      - sh_third_bash_center_hit
      - sh_third_bash_diagonal_right_hit
      - sh_third_bash_right_hit
    events_when_complete: dev_award_letter
