#config_version=5

show_player:
  mode_attract_started: attract_display_loop

slides:
  attract_started:
    widgets:
      - type: text
        text: ATTRACT MODE HI SEAN

slide_player:
  mode_attract_started: attract_started

# we are playing the song in sequence
# what we need is a reliable way to jump to landmark parts in the song reliably
# with a counter or a beat counter we can do this

# # could start a timer when 
# sound_loop_player:
#   mode_attract_started:
#     music:
#       action: play
#       sound_loop_set: gates_of_steel_set
#   # timer_foo_tick:
#   #   music:
#   #     action: jump_to
#   #     time: 0

# a - 10.148
# b - 28.189
# c - 
timers:
  foo:
    start_value: 0
    end_value: 1
    tick_interval: 2560ms
    restart_on_complete: true
    control_events:
      - action: start
        event: mode_attract_started
      

