#config_version=5

# TODO, figure out why I cant end this mode when I have a custom
# class.  do I need to add a mode_stop_events or something?

# mode:
#   code: attract.Attract

config:
  - widgets.yaml

show_player:
  mode_attract_started: attract_sparkle

slides:
  attract_started:
    widgets:
      - widget: row_1
      - widget: row_2
      - widget: row_1_blank
      - widget: row_2_blank
          
slide_player:
  mode_attract_started: attract_started

timers:
  foo:
    start_value: 0
    end_value: 1
    tick_interval: 2560ms
    restart_on_complete: true
    control_events:
      - action: start
        event: mode_attract_started
  attract_ticker:
    end_value: 32
    tick_interval: 300ms
    restart_on_complete: True
    control_events:
      - action: start
        event: mode_attract_started
