#config_version=5

mode:
  code: attract.Attract

config:
  - widgets.yaml

show_player:
  mode_attract_started: attract_display_loop

slides:
  attract_started:
    widgets:
      - widget: first_row_test
      - widget: second_row_test
      - widget: first_row_blank
      - widget: second_row_blank
          
slide_player:
  mode_attract_started: attract_started

timers:
  foo:
    start_value: 0
    end_value: 1
    tick_interval: 2560ms
    restart_on_complete: true
    control_events:
      - action: start
        event: mode_attract_started
  attract_ticker:
    end_value: 32
    tick_interval: 100ms
    restart_on_complete: True
    control_events:
      - action: start
        event: mode_attract_started
