#config_version=5

# TODO, figure out why I cant end this mode when I have a custom
# class.  do I need to add a mode_stop_events or something?

# mode:
#   code: attract.Attract

config:
  - widgets.yaml

# show_player:
#   mode_attract_started: attract_sparkle

slides:
  attract:
    widgets:
      - widget: row_1
      - widget: row_2

slide_player:
  mode_attract_started: attract
