#config_version=5

widgets:
  first_row_test:
    - type: text
      text: (machine|d_test_first)
      color: orange
      x: 10
      y: 500
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  second_row_test:
    - type: text
      text: (machine|d_test_second)
      color: orange
      x: 10
      y: 400
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  first_row:
    - type: text
      text: (machine|d0)(machine|d1)(machine|d2)(machine|d3)(machine|d4)(machine|d5)(machine|d6)(machine|d7)(machine|d8)(machine|d9)(machine|d10)(machine|d11)(machine|d12)(machine|d13)(machine|d14)(machine|d15)
      color: orange
      x: 10
      y: 500
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  second_row:
    - type: text
      text: (machine|d16)(machine|d17)(machine|d18)(machine|d19)(machine|d20)(machine|d21)(machine|d22)(machine|d23)(machine|d24)(machine|d25)(machine|d26)(machine|d27)(machine|d28)(machine|d29)(machine|d30)(machine|d31)
      color: orange
      x: 10
      y: 400
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  first_row_blank:
    - type: text
      text: '~~~~~~~~~~~~~~~~'
      color: gray
      x: 10
      y: 500
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 1
      opacity: .05
  second_row_blank:
    - type: text
      text: '~~~~~~~~~~~~~~~~'
      color: gray
      x: 10
      y: 400
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 1
      opacity: .05

