#config_version=5

mode:
  start_events: ball_starting
  priority: 100
  code: base.Base

config:
  - sequence_shots.yaml
  - shots.yaml
  - slides.yaml
  - widgets.yaml

slide_player:
  mode_base_started: base

variable_player:
  s_orbit_right_active:
    score: 1
