#config_version=5

widgets:
  base_row_1:
    - type: text
      text: (machine|d_base_1)
      color: orange
      x: 10
      y: 500
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  base_row_2:
    - type: text
      text: (machine|d_base_2)
      color: orange
      x: 10
      y: 400
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 2
  base_row_1_blank:
    - type: text
      text: '~~~~~~~~~~~~~~~~'
      color: gray
      x: 10
      y: 500
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 1
      opacity: .05
  base_row_2_blank:
    - type: text
      text: '~~~~~~~~~~~~~~~~'
      color: gray
      x: 10
      y: 400
      font_name: DSEG14Classic-Italic
      font_size: 60
      anchor_x: left
      anchor_y: top
      z: 1
      opacity: .05
