#config_version=5

shots:
  sh_foo_bash_left:
    profile: foo_bash
    base: sh_bash_left
    show_tokens:
      a:   l_serial_chain_0_13
  sh_foo_bash_diagonal_left:
    profile: foo_bash
    base: sh_bash_diagonal_left
    show_tokens:
      a:   l_serial_chain_0_14
  sh_foo_bash_center:
    profile: foo_bash
    base: sh_bash_center
    show_tokens:
      a:   l_serial_chain_0_15
  sh_foo_bash_diagonal_right:
    profile: foo_bash
    base: sh_bash_diagonal_right
    show_tokens:
      a:   l_serial_chain_0_16
  sh_foo_bash_right:
    profile: foo_bash
    base: sh_bash_right
    show_tokens:
      a:   l_serial_chain_0_17
  sh_foo_scoop:
    profile: foo_scoop
    base: sh_scoop
    show_tokens:
      a: l_serial_chain_0_29
      b: l_serial_chain_0_28
      c: l_serial_chain_0_27

