#config_version=5

mode:
  start_events: dev_start_eighth
  stop_events: dev_award_letter

config:
  - shots.yaml

event_player:
  mode_eighth_started.1: eighth_enable_ramp_left_lower
  mode_eighth_started.2: eighth_enable_orbit_left
  mode_eighth_started.3: eighth_enable_ramp_right
  mode_eighth_started.4: eighth_enable_orbit_right
  mode_eighth_started.5: eighth_enable_bash_left
  mode_eighth_started.6: eighth_enable_bash_diagonal_left
  mode_eighth_started.7: eighth_enable_bash_center
  mode_eighth_started.8: eighth_enable_bash_diagonal_right
  mode_eighth_started.9: eighth_enable_bash_right

accruals:
  eighth:
    events:
      - sh_eighth_ramp_left_lower_hit
      - sh_eighth_orbit_left_hit
      - sh_eighth_ramp_right_hit
      - sh_eighth_orbit_right_hit
      - sh_eighth_bash_left_hit
      - sh_eighth_bash_diagonal_left_hit
      - sh_eighth_bash_center_hit
      - sh_eighth_bash_diagonal_right_hit
      - sh_eighth_bash_right_hit
    events_when_complete: dev_award_letter
