#config_version=5

mode:
  code: drops.Drops
  start_events: ball_starting

state_machines:
  drops:
    states:
      start:
        label: placeholder
      urge_active:
        label: Uncontrollable urge hurry up mode started
        events_when_started: drops_state_urge_active_started
        events_when_stopped: drops_state_urge_active_stopped
    transitions:
      - source: start
        target: hurry_up_active
        events: drop_target_bank_drops_down
      - source: hurry_up_active
        target: start
        events: mode_urge_ended

event_player:
  mode_drops_started: drops_state_reset_bank
  mode_urge_ended: drops_state_reset_bank

