#config_version=5

shows:
  drops_show_award_1:
    - duration: .5
      lights:
        (a): red
        (b): stop
        (c): stop
    - duration: .5
      lights:
        (a): stop
        (b): stop
        (c): stop
  drops_show_award_2:
    - duration: .5
      lights:
        (a): red
        (b): yellow
        (c): stop
    - duration: .5
      lights:
        (a): red
        (b): stop
        (c): stop
  drops_show_award_3:
    - duration: .5
      lights:
        (a): red
        (b): yellow
        (c): green
    - duration: .5
      lights:
        (a): red
        (b): yellow
        (c): stop
  drops_show_mystery_lit:
    - time: 0
      events:
        drops_display_flash:
          seconds: 2
    - time: +16ms
      slides: drops
      events:
        drops_display_set_vars:
          r1: "!!!MYSTERY!IS!!!"
          r2: "!!!!!!LIT!!!!!!!"
    - time: 2
  drops_show_adda_ball:
    - time: 0
      events:
        drops_display_flash:
          seconds: 2
    - time: +16ms
      slides: drops
      events:
        drops_display_set_vars:
          r1: "!!!!!ADD-A!!!!!!"
          r2: "!!!!!!BALL!!!!!!"
    - time: 2
  drops_show_ball_locked:
    - time: 0
      events:
        drops_display_flash:
          seconds: 2
    - time: +16ms
      slides: drops
      events:
        drops_display_set_vars:
          r1: "!!!!!!BALL!!!!!!"
          r2: "!!!!!LOCKED!!!!!"
    - time: 2
  drops_show_urge_lit:
    - time: 0
      events:
        drops_display_flash:
          seconds: 2
    - time: +16ms
      slides: drops
      events:
        drops_display_set_vars:
          r1: "!UNCONTROLLABLE!"
          r2: "!!URGE!IS!LIT!!!"
    - time: 2




