#config_version=5

mode:
  start_events: ww_state_intro_stopped
  stop_events: timer_song_countdown_complete
  priority: 100

timers:
  song_countdown:
    start_value: 45
    end_value: -1
    direction: down
    start_running: True
