#config_version=5

mode:
  code: urge.Urge
  start_events: drops_state_urge_active_started
  # TODO: do i need to add ball_end here?
  stop_events: urge_state_end_started

config:
  - shot_profiles
  - shots
  - shows
  - slide_player
  - slides
  - state_machines
  - widgets

shows:
  urge_collected:
    - duration: 2
      variables:
        d_urge_1:
          action: set_machine
          string: 'UNCONTROLLABLE!!'
        d_urge_2:
          action: set_machine
          string: 'URGE!!!COLLECTED'

show_player:
  urge_state_collected_started:
    urge_collected:
      loops: 0
      events_when_played: urge_show_collected_started
      events_when_completed: urge_show_collected_completed

timers:
  urge:
    start_value: 30
    end_value: -1
    direction: down
    start_running: True
    control_events:
      - action: pause
        event: urge_state_paused_started
        value: 0
      - action: start
        event: urge_state_paused_stopped

