#config_version=5

mode:
  code: urge.Urge
  start_events: drops_state_urge_active_started
  stop_events: urge_state_end_started
  priority: 300

config:
  - shot_profiles
  - shots
  - shows
  - slides
  - state_machines
  - widgets

show_player:
  urge_state_collected_started{current_player.urges_collected < 3}:
    urge_collected_no_letter:
      loops: 0
      events_when_played: urge_show_collected_started
      events_when_completed: urge_show_collected_completed
  urge_state_collected_started{current_player.urges_collected == 3}:
    urge_and_letter_collected:
      loops: 0
      events_when_played: urge_show_collected_started
      events_when_completed: urge_show_collected_completed
  urge_state_collected_started{current_player.urges_collected > 3}:
    urge_collected:
      loops: 0
      events_when_played: urge_show_collected_started
      events_when_completed: urge_show_collected_completed

timers:
  urge:
    start_value: 30
    end_value: -1
    direction: down
    start_running: True
    control_events:
      - action: pause
        event: urge_state_paused_started
        value: 0
      - action: start
        event: urge_state_paused_stopped

