#config_version=5

mode:
  code: urge.Urge
  start_events: drops_state_urge_active_started

shows:
  urge_one_lit:
    - duration: 100ms
      lights:
        (a): red
    - duration: 100ms
      lights:
        (a): green
    - duration: 100ms
      lights:
        (a): yellow
  urge_one_unlit:
    - duration: 1
      lights:
        (a): off

shot_profiles:
  urge_one_indicator:
    advance_on_hit: False
    states:
      - name: unlit
        show: urge_one_unlit
      - name: lit
        show: urge_one_lit

# TODO: make it a collection of shots that can be the hurry up
# just going to make this the hurry up shot for now
shots:
  sh_urge_ramp_left_lower:
    hit_events: sh_rollover_button_hit
    profile: urge_one_indicator
    show_tokens:
      a: l_serial_chain_0_40

timers:
  urge_hurry_up:
    start_value: 30
    end_value: -1
    direction: down
    control_events:
      - action: start
        event: mode_urge_started
      - action: pause
        event: urge_state_hurry_up_paused_started
        value: 0
      - action: start
        event: urge_state_hurry_up_paused_stopped

state_machines:
  urge:
    states:
      start:
        label: hurry up is running
        events_when_started: urge_state_start_started
      paused:
        label: For when we need to pause the hurry up while its running, like during a mode intro sequence
        events_when_started: urge_state_paused_started
        events_when_stopped: urge_state_paused_stopped
    transitions:
      - source: start
        target: paused
        events: scoop_eject_paused_for_song_intro
      - source: paused
        target: start
        events: song_intro_complete
