#config_version=5

mode:
  start_events: ball_starting
  code: mpf.modes.autostack.code.autostack.Autostack

timers:
  autostack:
    start_value: 0
    end_value: 2
    tick_interval: .75s
    restart_on_complete: True
