#config_version=5

mode:
  start_events: ball_starting
  priority: 200
  code: bar.Bar

state_machines:
  bar:
    states:
      start:
        label: start state, both ramps lit, advanced when either is hit
        events_when_started: bar_start_started
      left_ramp_lit:
        label: advanced to right ramp lit when left is hit, bash timer is reset
        events_when_started: bar_left_ramp_lit_started
      right_ramp_lit:
        label: advanced to left ramp lit when right is hit, bash timer is reset
        events_when_started: bar_right_ramp_lit_started
      complete:
        label: collected X ramps
        events_when_started: bar_complete_started
    transitions:
      # beginning
      - source: start
        target: left_ramp_lit
        events: bar_right_hit
      - source: start
        target: right_ramp_lit
        events: bar_left_hit
      # smushing ramps
      - source: left_ramp_lit
        target: right_ramp_lit
        events: bar_left_hit
      - source: right_ramp_lit
        target: left_ramp_lit
        events: bar_right_hit
      # collect ramps hits
      - source: left_ramp_lit
        target: start
        events: bar_collect_ramp_hits, timer_bar_bash_timer_complete
      - source: right_ramp_lit
        target: start
        events: bar_collect_ramp_hits, timer_bar_bash_timer_complete

        
shows:
  bar_three_light_solid:
    - duration: -1
      lights:
        (a): blue
        (b): blue
        (c): blue
  bar_three_light_off:
    - duration: -1
      lights:
        (a): off
        (b): off
        (c): off
  bar_bash_off:
    - duration: -1
      lights:
        (a): off
        (b): off
        (c): off
        (d): off
        (e): off
  bar_bash_left_lit:
    - duration: -1
      lights:
        (a): red
        (b): red
        (c): red
        (d): off
        (e): off
  bar_bash_right_lit:
    - duration: -1
      lights:
        (a): off
        (b): off
        (c): red
        (d): red
        (e): red

shot_profiles:
  bar_three_light_shot:
    states:
      - name: lit
        show: bar_three_light_solid
      - name: complete
        show: bar_three_light_off
  bar_bash_alternating_side:
    states:
      - name: complete
        show: bar_bash_off
      - name: left_lit
        show: bar_bash_left_lit
      - name: right_lit
        show: bar_bash_right_lit

shots:
  bar_ramp_left:
    profile: bar_three_light_shot
    show_tokens:
      a: l_serial_chain_0_37
      b: l_serial_chain_0_38
      c: l_serial_chain_0_39
  bar_ramp_right:
    profile: bar_three_light_shot
    show_tokens:
      a: l_serial_chain_0_26
      b: l_serial_chain_0_25
      c: l_serial_chain_0_24
  bar_bash:
    profile: bar_bash_alternating_side
    show_tokens:
      a: l_serial_chain_0_13
      b: l_serial_chain_0_14
      c: l_serial_chain_0_15
      d: l_serial_chain_0_16
      e: l_serial_chain_0_17


        
variable_player:
  s_ramp_left_lower_active:
    score: 1000000
  s_ramp_right_active:
    score: 1000000

# # controlled in codee
timers:
  bar_bash_timer:
    start_value: 0
    end_value: 5
    start_running: False

counters:
   bar_ramp_count:
      count_events: bar_left_hit, bar_right_hit
      count_complete_value: 1000
      reset_on_complete: False
