#config_version=5

ball_devices:
  bd_trough:
    ball_switches: s_trough
    eject_coil: c_trough_eject
    tags: drain, home, trough
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
  bd_scoop:
    ball_switches: s_scoop
    eject_coil: c_scoop_eject
    eject_timeouts: 1s

