#config_version=5

ball_devices:
  bd_trough:
    ball_switches: s_trough, s_outlane_left, s_outlane_right
    eject_coil: c_trough_eject
    tags: drain, home, trough
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_plunger_eject
    mechanical_eject: true
  bd_scoop:
    ball_switches: s_scoop
    eject_coil: c_scoop_eject
    eject_timeouts: 1s

