#config_version=5

coils:
  c_flipper_lower_left_main:
    number: A1-B0-0
    default_pulse_ms: 23
  c_flipper_lower_left_hold:
    number: A1-B0-1
    default_hold_power: .4
    allow_enable: true
  c_flipper_lower_right_main:
    number: A1-B0-2
    default_pulse_ms: 23
  c_flipper_lower_right_hold:
    number: A1-B0-3
    allow_enable: true
    default_hold_power: .4
  c_flipper_mid_right_main:
    number: A1-B1-2
    default_pulse_ms: 15
  c_flipper_mid_right_hold:
    number: A1-B1-3
    allow_enable: true
    default_hold_power: .65
  c_flipper_upper_right_main:
    number: A1-B1-4
    default_pulse_ms: 15
  c_flipper_upper_right_hold:
    number: A1-B1-5
    default_hold_power: .5
    allow_enable: true
  c_pop_a:
    number: A3-B0-0
    default_pulse_power: 0.95
  c_pop_b:
    number: A3-B0-1
    default_pulse_power: 0.95
  c_pop_c:
    number: A3-B0-2
    default_pulse_power: 0.95
  c_diverter_left:
    number: A3-B0-3
    default_hold_power: .5
    allow_enable: true
  c_diverter_right:
    number: A3-B0-4
    default_hold_power: .5
    allow_enable: true
  c_scoop_eject:
    number: A3-B1-0
  c_drops:
    number: A3-B1-1
    default_pulse_ms: 50
  c_slings_left:
    number: A3-B1-2
    default_pulse_ms: 4
    default_pulse_power: 0.6
  c_slings_right:
    number: A3-B1-3
    default_pulse_ms: 4
    default_pulse_power: 0.6
# doesnt exist
  c_trough_eject:
    number: A10-B0-5
  c_plunger_eject:
    number: A10-B0-6

