#config_version=5

hardware:
  platform: p3_roc
  driverboards: pdb

p_roc:
  debug: True
  pd_led_boards:
    5:
      use_ws281x_0: True

config:
- autofire_coils.yaml
- ball_devices.yaml 
- coils.yaml
- drop_targets.yaml
- flippers.yaml
- keyboard.yaml
- lights.yaml
- modes.yaml
- playfields.yaml
- switches.yaml
- player_vars.yaml

sound_system:
  master_volume: 0.75
  tracks:
     music:
       type: sound_loop
       simultaneous_sounds: 1
       volume: 0.5
     voice:
       type: standard
       simultaneous_sounds: 1
       volume: 0.7
     sfx:
       type: standard
       simultaneous_sounds: 8
       volume: 0.4
       preload: yes

assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
      # preload for testing purposes only
      load: preload
    sfx:
      track: sfx
      load: preload
    voice:
      track: voice

sounds:
  gates_of_steel:
    max_queue_time: 0
  timing_x:
    max_queue_time: 0
  strange_pursuit:
    max_queue_time: 0
  charge:
    max_queue_time: 0
  charge_release:
    max_queue_time: 0

sound_loop_sets:
  gates_of_steel_set:
    sound: gates_of_steel
  timing_x_set:
    sound: timing_x
    events_when_played: timing_x_started
    events_when_stopped: timing_x_stopped
    events_when_looping: timing_x_looped

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: SOME PINBALL GAME!
        font_size: 100
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide
