#config_version=5

machine_vars:
  # display variables for modes
  d_attract_1:
    initial_value: 'PRESS!START!!!!!'
    value_type: str
    persist: False
  d_attract_2:
    initial_value: '!!!!!!PRESS!STAR'
    value_type: str
    persist: False
  d_test_1:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_test_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_base_1:
    initial_value: 'BASE!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_base_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_song_select_1:
    initial_value: 'SONG!SELECT!!!!!'
    value_type: str
    persist: False
  d_song_select_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_ww_1:
    initial_value: 'WIGGLY!WORLD!!!!'
    value_type: str
    persist: False
  d_ww_2:
    initial_value: 'WIGGLY!WORLD!!!!'
    value_type: str
    persist: False
  d_drops_1:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_drops_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_urge_1:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_urge_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_dev_1:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False
  d_dev_2:
    initial_value: '!!!!!!!!!!!!!!!!'
    value_type: str
    persist: False

