#config_version=5

modes:
  # testing
  - test
  # management
  - base
  - bash_resolver
  - charged_flips
  - drops
  - song_select
  - song_countdown
  # uncontrollable urge hurry ups
  - urge
  # songs ('modes' in pinball parlance)
  - bar
  - wiggly_world
  # ball over
  - bonus
