#config_version=5

modes:
  # attract
  # constantly running
  - base
  - bash_resolver
  - charged_flips
  - song_select
  # songs ('modes' in pinball parlance)
  - foo               
  - bar
  # ball over
  - bonus
