#config_version=5

modes:
  # testing
  # - test
  # management
  - autostack
  - base
  - bash_resolver
  - charged_flips
  - drops
  - song_select
  # # uncontrollable urge hurry ups
  # - urge
  # # songs ('modes' in pinball parlance)
  - bonus
