#config_version=5

modes:
  # testing
  # - test
  # management
  # - autostack
  - base
  - bash_resolver
  - charged_flips
  - dev
  - drops
  # song challenges
  - first
  # # uncontrollable urge hurry ups
  # - urge
  # # songs ('modes' in pinball parlance)
  - bonus
