#config_version=5

modes:
  # attract
  # perennial
  - base
  - bash_resolver
  - charged_flips
  # management management
  - song_select
  - song_countdown
  # songs ('modes' in pinball parlance)
  - foo               
  - bar
  - wiggly_world
  # ball over
  - bonus
