#config_version=5

switches:
  s_start:
    number: 100
    tags: start
  s_left_flipper:
    number: A0-B0-0
    tags: left_flipper
  s_right_flipper:
    number: A0-B0-1
    tags: right_flipper
  s_charge_right:
    number: A0-B0-2
  s_charge_left:
    number: A0-B0-3
  s_ramp_left_lower:
    number: A0-B0-4
  s_pop_a:
    number: A0-B1-1
  s_pop_b:
    number: A0-B1-0
  s_pop_c:
    number: A0-B1-2
  s_bash_left:
    number: A0-B1-3
  s_bash_right:
    number: A0-B1-4
  s_bash_forward:
    number: A0-B1-5
  s_scoop:
    number: A0-B1-6
    type: 'NC'
  s_ramp_right:
    number: A0-B1-7
  s_orbit_right:
    number: A2-B0-0
    tags: playfield_active
  s_inner_loop:
    number: A2-B0-1
  s_right_lair_right:
    number: A2-B0-2
  s_right_lair_center:
    number: A2-B0-3
  s_right_lair_left:
    number: A2-B0-4
  s_gate_right:
    number: A2-B0-5
  s_top_lane_right:
    number: A2-B0-6
  s_top_lane_center:
    number: A2-B0-7
  s_top_lane_left:
    number: A2-B1-0
  s_zone_left_right:
    number: A2-B1-1
  s_zone_left_center:
    number: A2-B1-2
  s_zone_left_left:
    number: A2-B1-3
  s_orbit_left:
    number: A2-B1-4
  # not used
  s_turnaround_right:
    number: A2-B1-5
  # not used
  s_turnaround_left:
    number: A2-B1-6
  # not hooked up yet
  s_ramp_left_upper:
    number: A2-B1-7
  s_shitty_target:
    number: A4-B0-0
  s_thin_standup_right:
    number: A4-B0-1
  s_thin_standup_left:
    number: A4-B0-2
  s_drop_bottom:
    number: A4-B0-3
    type: 'NC'
  s_drop_middle:
    number: A4-B0-4
    type: 'NC'
  s_drop_top:
    number: A4-B0-5
    type: 'NC'
  s_rollover_button:
    number: A4-B0-6
  s_outlane_right:
    number: A4-B1-0
  s_right_inlane:
    number: A4-B1-1
  s_sling_right_top:
    number: A4-B1-2
  s_sling_right_bottom:
    number: A4-B1-3
  s_sling_left_top:
    number: A4-B1-4
  s_sling_left_bottom:
    number: A4-B1-5
  s_left_inlane:
    number: A4-B1-6
  s_outlane_left:
    number: A4-B1-7
  # fake convenience switches
  s_drain:
    number: A10-B0-0
  s_trough:
    number: A10-B0-1
    type: NC
  s_plunger:
    number: A10-B0-2
  s_award_letter:
    number: A10-B0-3

