#config_version=5

switches:
  s_start:
    number: 100
    tags: start
  s_left_flipper:
    number: A0-B0-0
    tags: left_flipper
  s_right_flipper:
    number: A0-B0-1
    tags: right_flipper
  s_pop_a:
    number: A0-B1-1
  s_pop_b:
    number: A0-B1-0
  s_pop_c:
    number: A0-B1-2
  s_newton_left:
    number: A0-B1-3
  s_newton_right:
    number: A0-B1-4
  s_newton_forward:
    number: A0-B1-5
  s_scoop:
    number: A0-B1-6
    type: 'NC'
  s_dead_end_right:
    number: A0-B1-7
  s_right_orbit:
    number: A2-B0-0
    tags: playfield_active
  s_inner_loop:
    number: A2-B0-1
  s_right_lair_right:
    number: A2-B0-2
  s_right_lair_center:
    number: A2-B0-3
  s_right_lair_left:
    number: A2-B0-4
  s_right_lair_gate:
    number: A2-B0-5
  s_top_lane_right:
    number: A2-B0-6
  s_top_lane_center:
    number: A2-B0-7
  s_top_lane_left:
    number: A2-B1-0
  s_left_zone_right:
    number: A2-B1-1
  s_left_zone_center:
    number: A2-B1-2
  s_left_zone_left:
    number: A2-B1-3
  s_left_orbit:
    number: A2-B1-4
  s_turnaround_right:
    number: A2-B1-5
  s_turnaround_left:
    number: A2-B1-6
  s_turnaround_gate:
    number: A2-B1-7
  s_shitty_target:
    number: A4-B0-0
  s_thin_standup_right:
    number: A4-B0-1
  s_thin_standup_left:
    number: A4-B0-2
  s_drop_bottom:
    number: A4-B0-3
    type: 'NC'
  s_drop_middle:
    number: A4-B0-4
    type: 'NC'
  s_drop_top:
    number: A4-B0-5
    type: 'NC'
  s_dead_end_left:
    number: A4-B0-6
  s_right_outlane:
    number: A4-B1-0
  s_right_inlane:
    number: A4-B1-1
  s_right_sling_top:
    number: A4-B1-2
  s_right_sling_bottom:
    number: A4-B1-3
  s_left_sling_top:
    number: A4-B1-4
  s_left_sling_bottom:
    number: A4-B1-5
  s_left_inlane:
    number: A4-B1-6
  s_left_outlane:
    number: A4-B1-7
# fake
  s_drain:
    number: A10-B0-0
  s_trough_1:
    number: A10-B0-1
    type: NC
  s_plunger:
    number: A10-B0-2

