#config_version=5

mode:
  start_events: dev_start_second
  stop_events: dev_award_letter

config:
  - shots.yaml

event_player:
  # mode_second_started.1: second_enable_bash_left
  mode_second_started.2: second_enable_bash_diagonal_left
  mode_second_started.3: second_enable_bash_center
  mode_second_started.4: second_enable_bash_diagonal_right
  # mode_second_started.5: second_enable_bash_right

accruals:
  second:
    events:
      # - sh_second_bash_left_hit
      - sh_second_bash_diagonal_left_hit
      - sh_second_bash_center_hit
      - sh_second_bash_diagonal_right_hit
      # - sh_second_bash_right_hit
    events_when_complete: dev_award_letter
