#config_version=5

mode:
  start_events: dev_start_seventh
  stop_events: dev_award_letter

config:
  - shots.yaml

event_player:
  mode_seventh_started.1: seventh_enable_ramp_left_lower
  mode_seventh_started.2: seventh_enable_orbit_left
  mode_seventh_started.3: seventh_enable_ramp_right
  mode_seventh_started.4: seventh_enable_orbit_right
  mode_seventh_started.5: seventh_enable_bash_left
  mode_seventh_started.6: seventh_enable_bash_diagonal_left
  mode_seventh_started.7: seventh_enable_bash_center
  mode_seventh_started.8: seventh_enable_bash_diagonal_right
  mode_seventh_started.9: seventh_enable_bash_right

accruals:
  seventh:
    events:
      - sh_seventh_ramp_left_lower_hit
      - sh_seventh_orbit_left_hit
      - sh_seventh_ramp_right_hit
      - sh_seventh_orbit_right_hit
      - sh_seventh_bash_left_hit
      - sh_seventh_bash_diagonal_left_hit
      - sh_seventh_bash_center_hit
      - sh_seventh_bash_diagonal_right_hit
      - sh_seventh_bash_right_hit
    events_when_complete: dev_award_letter
