#config_version=5

shot_profiles:
  song_select_bash:
    autostack: True
    states:
      - name: charge_0
        show: song_select_bash_charge_0
      - name: charge_1
        show: song_select_bash_charge_1
      - name: charge_2
        show: song_select_bash_charge_2
      - name: unlit
        show: song_select_bash_unlit
      - name: song_selected
        show: song_select_selected
  song_select_scoop:
    autostack: True
    states:
      - name: unlit
        show: song_select_scoop_unlit
      - name: lit
        show: song_select_scoop_lit

