#config_version=5

shows:
  song_select_bash_charge_0:
    - duration: -1
      lights:
        (a): yellow
  song_select_bash_charge_1:
    - duration: -1
      lights:
        (a): orange
  song_select_bash_charge_2:
    - duration: -1
      lights:
        (a): red
  song_select_bash_unlit:
    - duration: -1
      lights:
        (a): off
  song_select_selected:
    - duration: -1
      lights:
        (a): white
  song_select_scoop_unlit:
    - duration: -1
      lights:
        (a): off
        (b): off
        (c): off
  song_select_scoop_lit:
    - duration: .1
      lights:
        (a): blue
        (b): off
        (c): off
    - duration: .1
      lights:
        (a): off
        (b): blue
        (c): off
    - duration: .1
      lights:
        (a): off
        (b): off
        (c): blue
