#config_version=5

mode:
  start_events: ball_starting, code_song_stopped
  stop_events: state_song_select_wait_started
  code: song_select.SongSelect
  priority: 200

config:
  - shot_profiles.yaml
  - shots.yaml
  - shows.yaml
  - slides.yaml
  - state_machines.yaml
  - widgets.yaml

slide_player:
  code_song_select_show_selected_song:
    song_select:
      action: play
      # expire value needs to match printer.flash call in code
      expire: 2
