#config_version=5

mode:
  start_events: ball_starting
  code: song_select.SongSelect
  priority: 100

shows:
  song_select_bash_charge_0:
    - duration: -1
      lights:
        (a): yellow
  song_select_bash_charge_1:
    - duration: -1
      lights:
        (a): orange
  song_select_bash_charge_2:
    - duration: -1
      lights:
        (a): red
  song_select_bash_unlit:
    - duration: -1
      lights:
        (a): off
  song_select_scoop_unlit:
    - duration: -1
      lights:
        (a): off
        (b): off
        (c): off
  song_select_scoop_lit:
    - duration: .1
      lights:
        (a): blue
        (b): off
        (c): off
    - duration: .1
      lights:
        (a): off
        (b): blue
        (c): off
    - duration: .1
      lights:
        (a): off
        (b): off
        (c): blue


shot_profiles:
  song_select_bash:
    states:
      - name: charge_0
        show: song_select_bash_charge_0
      - name: charge_1
        show: song_select_bash_charge_1
      - name: charge_2
        show: song_select_bash_charge_2
      - name: unlit
        show: song_select_bash_unlit
  song_select_scoop:
    states:
      - name: unlit
        show: song_select_scoop_unlit
      - name: lit
        show: song_select_scoop_lit

shots:
  sh_song_select_bash_left:
    profile: song_select_bash
    hit_events: seq_bash_left_hit
    show_tokens:
      a:   l_serial_chain_0_13
  sh_song_select_bash_diagonal_left:
    profile: song_select_bash
    hit_events: seq_bash_diagonal_left_hit
    show_tokens:
      a:   l_serial_chain_0_14
  sh_song_select_bash_center:
    profile: song_select_bash
    hit_events: seq_bash_center_hit
    show_tokens:
      a:   l_serial_chain_0_15
  sh_song_select_bash_diagonal_right:
    profile: song_select_bash
    hit_events: seq_bash_diagonal_right_hit
    show_tokens:
      a:   l_serial_chain_0_16
  sh_song_select_bash_right:
    profile: song_select_bash
    hit_events: seq_bash_right_hit
    show_tokens:
      a:   l_serial_chain_0_17
  sh_song_select_scoop:
    profile: song_select_scoop
    show_tokens:
      a: l_serial_chain_0_29
      b: l_serial_chain_0_28
      c: l_serial_chain_0_27

state_machines:
  song_select:
    states:
      start:
        label: placeholder, i figure mode start will set this to the right state if state doesnt persist
      skill_shot:
        label: placeholder, but figure that on plunge there will be a short time to qualify a mode instantly
      qualifying:
        label: here we hit the bash the booji until the its ready
      qualified:
        label: mode is ready to start at the scoop
      song_wait:
        label: song is about to start, cleanup and wait for shows to finish
        events_when_started: song_select_song_wait_started
      song_running:
        label: song has started, using this state primarily to wait
        events_when_started: song_select_song_running_started
    transitions:
      - source: start
        target: skill_shot
        events: song_select_state_start_complete
      - source: skill_shot
        target: qualifying
        events: timer_song_select_skill_shot_timeout_complete
      - source: qualifying
        target: qualified
        events: song_select_state_qualifying_complete
      - source: qualified
        target: song_wait
        # todo - due to how shot inheritance works i have to use the base scoop hit here
        events: sh_scoop_hit
      - source: song_wait
        target: song_running
        events: balldevice_bd_scoop_ball_eject_success
      - source: song_running
        target: start
        # todo add the right drain event
        events: some_drain_event

timers:
  song_select_skill_shot_timeout:
    tick_interval: 1s
    end_value: 4
    control_events:
      - action: start
        event: song_select_state_start_complete
      - action: reset
        event: timer_song_select_skill_shot_timeout_complete


