#config_version=5

mode:
  start_events: ball_starting, code_song_stopped
  stop_events: state_song_select_wait_started
  code: song_select.SongSelect
  priority: 200

config:
  - shot_profiles.yaml
  - shots.yaml
  - shows.yaml
  - slide_player.yaml
  - slides.yaml
  - state_machines.yaml
  - widgets.yaml
