#config_version=5

widget_player:
  song_select_0_status_unselected:
    song_select_0_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: gray
  song_select_0_status_selected:
    song_select_0_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: white
  song_select_0_status_running:
    song_select_0_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: red
  song_select_0_status_completed:
    song_select_0_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: green
  song_select_1_status_unselected:
    song_select_1_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: gray
  song_select_1_status_selected:
    song_select_1_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: white
  song_select_1_status_running:
    song_select_1_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: red
  song_select_1_status_completed:
    song_select_1_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: green
  song_select_2_status_unselected:
    song_select_2_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: gray
  song_select_2_status_selected:
    song_select_2_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: white
  song_select_2_status_running:
    song_select_2_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: red
  song_select_2_status_completed:
    song_select_2_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: green
  song_select_3_status_unselected:
    song_select_3_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: gray
  song_select_3_status_selected:
    song_select_3_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: white
  song_select_3_status_running:
    song_select_3_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: red
  song_select_3_status_completed:
    song_select_3_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: green
  song_select_4_status_unselected:
    song_select_4_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: gray
  song_select_4_status_selected:
    song_select_4_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: white
  song_select_4_status_running:
    song_select_4_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: red
  song_select_4_status_completed:
    song_select_4_song_widget:
      action: update
      slide: base_slide
      widget_settings:
        color: green

widgets:
  song_select_section_title_widget:
    - type: text
      text: SONGS
      x: 10
      y: 580
      font_size: 20
      anchor_x: left  
  song_select_0_song_widget:
    - type: text
      text: Gates of Steel
      x: 10
      y: 560
      font_size: 20
      anchor_x: left
      color: gray
  song_select_1_song_widget:
    - type: text
      text: Strange Pursuit
      x: 10
      y: 540
      font_size: 20
      anchor_x: left
      color: gray
  song_select_2_song_widget:
    - type: text
      text: Girl U Want
      x: 10
      y: 520
      font_size: 20
      anchor_x: left
      color: gray
  song_select_3_song_widget:
    - type: text
      text: Cold War
      x: 10
      y: 500
      font_size: 20
      anchor_x: left
      color: gray
  song_select_4_song_widget:
    - type: text
      text: Gut Feelin
      x: 10
      y: 480
      font_size: 20
      anchor_x: left
      color: gray
  bazzle_widget_None:
    - type: text
      text: Test
      x: 10
      y: 460
      font_size: 20
      anchor_x: left
      color: green
  bazzle_widget_0:
    - type: text
      text: Test
      x: 10
      y: 460
      font_size: 20
      anchor_x: left
      color: green
  bazzle_widget_1:
    - type: text
      text: Test
      x: 10
      y: 460
      font_size: 20
      anchor_x: left
      color: white
  bazzle_widget_2:
    - type: text
      text: Test
      x: 10
      y: 460
      font_size: 20
      anchor_x: left
      color: red
  bazzle_widget_3:
    - type: text
      text: Test
      x: 10
      y: 460
      font_size: 20
      anchor_x: left
      color: black
